name: Deploy AWS Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  STORAGE_STACK_NAME: sales-cfn-storage-stack
  PIPELINE_STACK_NAME: sales-cfn-pipeline-stack
  INPUT_BUCKET: priya-cfn-glue-input-2026
  OUTPUT_BUCKET: priya-cfn-glue-output-2026
  SCRIPTS_BUCKET: priya-cfn-glue-scripts-2026

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::719287408908:role/GitHubActionsDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy S3 storage stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/storage.yaml \
            --stack-name ${STORAGE_STACK_NAME} \
            --region ${AWS_REGION} \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              InputBucketName=${INPUT_BUCKET} \
              OutputBucketName=${OUTPUT_BUCKET} \
              ScriptsBucketName=${SCRIPTS_BUCKET}

      - name: Package Lambda
        run: |
          cd lambda
          zip -j lambda_function.zip lambda_function.py

      - name: Upload Lambda package
        run: |
          aws s3 cp \
            lambda/lambda_function.zip \
            s3://${SCRIPTS_BUCKET}/lambda/lambda_function.zip

      - name: Upload Glue script
        run: |
          aws s3 cp \
            glue/sales_transformation.py \
            s3://${SCRIPTS_BUCKET}/glue/sales_transformation.py

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://cloudformation/template.yaml

      - name: Deploy pipeline stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/template.yaml \
            --stack-name ${PIPELINE_STACK_NAME} \
            --region ${AWS_REGION} \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              InputBucketName=${INPUT_BUCKET} \
              OutputBucketName=${OUTPUT_BUCKET} \
              ScriptsBucketName=${SCRIPTS_BUCKET} \
              WorkflowName=sales-cfn-pipeline-workflow \
              CrawlerName=sales-cfn-input-crawler \
              JobName=sales-cfn-transformation-job \
              DatabaseName=sales_cfn_pipeline_db

      - name: Deployment completed
        run: |
          echo "CloudFormation verification pipeline deployed successfully."