name: Destroy CFN Verification Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  PIPELINE_STACK_NAME: sales-cfn-pipeline-stack
  STORAGE_STACK_NAME: sales-cfn-storage-stack

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::719287408908:role/GitHubActionsDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Delete pipeline stack
        run: |
          aws cloudformation delete-stack \
            --stack-name ${PIPELINE_STACK_NAME} \
            --region ${AWS_REGION}

      - name: Wait for pipeline stack deletion
        run: |
          aws cloudformation wait stack-delete-complete \
            --stack-name ${PIPELINE_STACK_NAME} \
            --region ${AWS_REGION}

      - name: Delete storage stack
        run: |
          aws cloudformation delete-stack \
            --stack-name ${STORAGE_STACK_NAME} \
            --region ${AWS_REGION}

      - name: Wait for storage stack deletion
        run: |
          aws cloudformation wait stack-delete-complete \
            --stack-name ${STORAGE_STACK_NAME} \
            --region ${AWS_REGION}

      - name: Destroy completed
        run: |
          echo "CloudFormation verification environment deleted successfully."