name: Destroy AWS Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  STACK_NAME: sales-pipeline-stack

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::719287408908:role/GitHubActionsDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Delete CloudFormation stack
        run: |
          aws cloudformation delete-stack \
            --stack-name ${STACK_NAME} \
            --region ${AWS_REGION}

      - name: Wait for stack deletion
        run: |
          aws cloudformation wait stack-delete-complete \
            --stack-name ${STACK_NAME} \
            --region ${AWS_REGION}

      - name: Destroy completed
        run: |
          echo "CloudFormation stack deleted successfully."